entrypoint: foreman start --formation "$FORMATION"
env: flex
runtime: custom
automatic_scaling: 
  min_num_instances: 2
  max_num_instances: 4
  cpu_utilization:
    target_utilization: 0.4
resources:
  memory_gb: 1.5

env_variables:
  SECRET_KEY_BASE: 63077c247615df200d667c77ca65ad4de37ffb523aa03f6b59a9139d82189b9e483e8487994e354dd3723e6115e45c5d3b2a492447cedf721fbc5a7432ff94dd
  MYSQL_USER: luft
  MYSQL_PASSWORD: eitheigaip4Ex4es5aideweigu4Oopho
  MYSQL_DATABASE: luft
  MYSQL_SOCKET_PATH: /cloudsql/luft-184208:europe-west1:luft
  FORMATION: web=1


# health_check:
#   enable_health_check: False

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
  
beta_settings:
  cloud_sql_instances: luft-184208:europe-west1:luft